/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPartnersRouteImport } from './routes/_app/partners'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppCommissionsRouteImport } from './routes/_app/commissions'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppBackupsRouteImport } from './routes/_app/backups'
import { Route as AppActivitiesRouteImport } from './routes/_app/activities'
import { Route as AppPartnersIdRouteImport } from './routes/_app/partners.$id'
import { Route as AppClientsDuplicatesRouteImport } from './routes/_app/clients.duplicates'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients.$id'
import { Route as ApiPublicHooksBackupRouteImport } from './routes/api/public/hooks/backup'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsRoute = AppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersIdRoute = AppPartnersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPartnersRoute,
} as any)
const AppClientsDuplicatesRoute = AppClientsDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const ApiPublicHooksBackupRoute = ApiPublicHooksBackupRouteImport.update({
  id: '/api/public/hooks/backup',
  path: '/api/public/hooks/backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities': typeof AppActivitiesRoute
  '/backups': typeof AppBackupsRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/commissions': typeof AppCommissionsRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/partners': typeof AppPartnersRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/duplicates': typeof AppClientsDuplicatesRoute
  '/partners/$id': typeof AppPartnersIdRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities': typeof AppActivitiesRoute
  '/backups': typeof AppBackupsRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/commissions': typeof AppCommissionsRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/partners': typeof AppPartnersRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/duplicates': typeof AppClientsDuplicatesRoute
  '/partners/$id': typeof AppPartnersIdRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/backups': typeof AppBackupsRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/partners': typeof AppPartnersRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/clients/duplicates': typeof AppClientsDuplicatesRoute
  '/_app/partners/$id': typeof AppPartnersIdRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/activities'
    | '/backups'
    | '/clients'
    | '/commissions'
    | '/crm'
    | '/dashboard'
    | '/opportunities'
    | '/partners'
    | '/settings'
    | '/users'
    | '/clients/$id'
    | '/clients/duplicates'
    | '/partners/$id'
    | '/api/public/hooks/backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/activities'
    | '/backups'
    | '/clients'
    | '/commissions'
    | '/crm'
    | '/dashboard'
    | '/opportunities'
    | '/partners'
    | '/settings'
    | '/users'
    | '/clients/$id'
    | '/clients/duplicates'
    | '/partners/$id'
    | '/api/public/hooks/backup'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/activities'
    | '/_app/backups'
    | '/_app/clients'
    | '/_app/commissions'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/opportunities'
    | '/_app/partners'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/clients/$id'
    | '/_app/clients/duplicates'
    | '/_app/partners/$id'
    | '/api/public/hooks/backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksBackupRoute: typeof ApiPublicHooksBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backups': {
      id: '/_app/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AppBackupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners/$id': {
      id: '/_app/partners/$id'
      path: '/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof AppPartnersIdRouteImport
      parentRoute: typeof AppPartnersRoute
    }
    '/_app/clients/duplicates': {
      id: '/_app/clients/duplicates'
      path: '/duplicates'
      fullPath: '/clients/duplicates'
      preLoaderRoute: typeof AppClientsDuplicatesRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/api/public/hooks/backup': {
      id: '/api/public/hooks/backup'
      path: '/api/public/hooks/backup'
      fullPath: '/api/public/hooks/backup'
      preLoaderRoute: typeof ApiPublicHooksBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsDuplicatesRoute: typeof AppClientsDuplicatesRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsDuplicatesRoute: AppClientsDuplicatesRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppPartnersRouteChildren {
  AppPartnersIdRoute: typeof AppPartnersIdRoute
}

const AppPartnersRouteChildren: AppPartnersRouteChildren = {
  AppPartnersIdRoute: AppPartnersIdRoute,
}

const AppPartnersRouteWithChildren = AppPartnersRoute._addFileChildren(
  AppPartnersRouteChildren,
)

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppBackupsRoute: typeof AppBackupsRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppPartnersRoute: typeof AppPartnersRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppBackupsRoute: AppBackupsRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppCommissionsRoute: AppCommissionsRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppPartnersRoute: AppPartnersRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksBackupRoute: ApiPublicHooksBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
